title: <p align="center"> Akik Ranade </p>
logo: /assets/IMG-2.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/akikranade/">LinkedIn</a> |
  <a href="https://github.com/akikranade">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  <br>
  </p>



theme: jekyll-theme-minimal
